name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "Hello first-job"
      - name: finish
        run: echo "Finish first-job"
    
    
