name: Reusable Deploy
on: 
 workflow_call:
    inputs:
        artifact-name:
            description: The name of the demployement element
            required: false
            default: dist
            type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/download-artifact@v3
            with:
              name: ${{inputs.artifact-name}}
          - name: Output Deploy
            run: echo "Deploying..."